Biblioteca.Web/Controllers/AutorController.cs
using System;
using Biblioteca.Dto;
using System.Diagnostics;
using Biblioteca.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Biblioteca.Infrastructure;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using Biblioteca.Web.Mapper.ModelToDto;
using Biblioteca.Application.Services.Interfaces;

namespace Biblioteca.Web.Controllers
{
    /// <summary>
    /// Class for autorController. (Controller)
    /// </summary>
    public class AutorController : BaseController
    {
        
        private readonly IService<autorDto> service;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="service"></param>
        public AutorController(
            ILogger<AutorController> logger,
            IService<autorDto> service) : base(logger)
        {
            this.service = service;
        }

        /// <summary>
        /// Get index view.
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            ICollection<autorDto> result = new List<autorDto>();
            try
            {
                result = this.service.all();
            }
            catch (Exception ex)
            {
                HandleExecption(ex);
            }
            return View(result);
        }

        /// <summary>
        /// Get create view.
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind] autorModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    this.service.add(autorModelMap.map(model));
                }
                catch (Exception ex)
                {
                    HandleExecption(ex);
                }

                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Biblioteca.Web/Controllers/EditorialController.cs
using System;
using Biblioteca.Dto;
using System.Diagnostics;
using Biblioteca.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Biblioteca.Infrastructure;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using Biblioteca.Web.Mapper.ModelToDto;
using Biblioteca.Application.Services.Interfaces;

namespace Biblioteca.Web.Controllers
{
    /// <summary>
    /// Class for editorialController. (Controller)
    /// </summary>
    public class EditorialController : BaseController
    {

        private readonly IService<editorialDto> service;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="service"></param>
        public EditorialController(
            ILogger<EditorialController> logger,
            IService<editorialDto> service) : base(logger)
        {
            this.service = service;
        }

        /// <summary>
        /// Get index view.
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            ICollection<editorialDto> result = new List<editorialDto>();
            try
            {
                result = this.service.all();
            }
            catch (Exception ex)
            {
                HandleExecption(ex);
            }
            return View(result);
        }

        /// <summary>
        /// Get create view.
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind] editorialModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    this.service.add(editorialModelMap.map(model));
                }
                catch (Exception ex)
                {
                    HandleExecption(ex);
                }

                return RedirectToAction(nameof(Index));
            }
            return View();
        }
    }
}

Biblioteca.Web/Controllers/LibroController.cs
using System;
using System.Linq;
using Biblioteca.Dto;
using System.Diagnostics;
using Biblioteca.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Biblioteca.Infrastructure;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using Biblioteca.Web.Mapper.ModelToDto;
using Microsoft.AspNetCore.Mvc.Rendering;
using Biblioteca.Application.Services.Interfaces;

namespace Biblioteca.Web.Controllers
{
    /// <summary>
    /// Class for libroController. (Controller)
    /// </summary>
    public class LibroController : BaseController
    {
        private readonly IService<libroDto> service;
        private readonly IService<autorDto> autorService;
        private readonly IService<editorialDto> editorialService;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="service"></param>
        public LibroController(
            ILogger<LibroController> logger,
            IService<libroDto> service,
            IService<autorDto> autorService,
            IService<editorialDto> editorialService) : base(logger)
        {
            this.service = service;
            this.autorService = autorService;
            this.editorialService = editorialService;
        }

        /// <summary>
        /// Get index view.
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            ICollection<libroDto> result = new List<libroDto>();
            try
            {
                result = this.service.all();
            }
            catch (Exception ex)
            {
                HandleExecption(ex);
            }
            return View(result);
        }

        /// <summary>
        /// Get create view.
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            var vm = new libroModel();
            vm.editoriales = this.editorialService.all().Select(x => new SelectListItem() { Text = x.nombre, Value = x.id.ToString() }).ToList();
            vm.autores = this.autorService.all().Select(x => new SelectListItem() { Text = x.nombre, Value = x.id.ToString() }).ToList();
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind] libroModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var dto = libroModelMap.map(model);
                    this.service.add(dto);
                }
                catch (Exception ex)
                {
                    HandleExecption(ex);
                }

                return RedirectToAction(nameof(Index));
            }
            return View();
        }
    }
}

Biblioteca.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Biblioteca</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Biblioteca</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libro" asp-action="Index">Libros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Autor" asp-action="Index">Autores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Editorial" asp-action="Index">Editoriales</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MillionAndUp - Rolando García M. 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>